apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
        - name: payment-service
          image: kedikebba/payment-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: nextService
            - name: BANK_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: bankService
            - name: PAYPAL_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: paypalService
            - name: CREDITCARD_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: creditCardService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: service-api-key
            - name: ENC_SECRET
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: secret-key-enc
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: payment-service-config
                  key: database-name
            - name: GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: payment-service-config
                  key: group_id
            - name: KAFKA
              valueFrom:
                secretKeyRef:
                  name: payment-service-config
                  key: kafka
            #MYSQL
