apiVersion: v1
kind: Secret
metadata:
  name: paymentservice-secrets
type: Opaque
data:
  service-api-key: czVEVWFyVWwmYlRAWEcqTEtGTmkzVzI=
  mysql-root-password: cGFzc3dvcmQ=  #password
  secretEncryptionKey: RW50ZXJwcmlzZUFyY2hpdGVjdHVyZUNTNTI0QFZFUklMTEhBTEw=

